/**
 * Reset fis cli command.
 * @param fis
 */
module.exports = function(fis) {
  var cli = fis.cli;
  cli.version = function() {
    var content = ['',
      '  v' + cli.info.version,
      ''
    ].join('\n');

    var logo = [
      '  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
      '  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM@@@M@MMMMMMMMMMM@MMMMMWM@MMMMMMMMMMMM@@MM',
      '  MZ      S@MMMMMMMMMMMZ      2MMM                  MMM;                 MM',
      '  MZ   8   2MMMMMMMMMMB   8   2MMMSXS2SaZ    Za2SSXSMMM2XSS22Z    ZaSSSXXMM',
      '  MZ   WM   BMMMMMMMMM   WM   ZMMMMMMMMMM    MMMMMMMMMMMMMMMMM    MMMMMMMMM',
      '  M8   BMZ   MMMMMMMMZ   MM   ZMMMMMMMMMM    MMMMMMMMMMMMMMMMM    @MMMMMMMM',
      '  M8   8M@   ZMMMMMM@   WMM   ZMMMMMMMMMM    @MMMMMMMMMMMMMMMM    @MMMMMMMM',
      '  M8   8MMa   WMMMMM2  aMMW   ZMMMMMMMMMM    @MMMMMMMMMMMMMMMM    @MMMMMMMM',
      '  MZ   ZMMM   aMMMM8   @MMW   ZMMMMMMMMMM    WMMMMMMMMMMMMMMMM    @MMMMMMMM',
      '  M8   ZMMM8   0MMM   ZMMMB   ZMMMMMMMMMM    @MMMMMMMMMMMMMMMM    @MMMMMMMM',
      '  M8   ZMMMM    MMZ   MMMMW   ZMMMMMMMMMM    @MMMMMMMMMMMMMMMM    @MMMMMMMM',
      '  M8   ZMMMM0   B@   BMMMMB   ZMMMMMMMMMM    @MMMMMMMMMMMMMMMM    WMMMMMMMM',
      '  M8   ZMMMMM2      aMMMMMW   ZMMMMMMMMMM    @MMMMMMMMMMMMMMMM    @MMMMMMMM',
      '  M8   ZMMMMM@      @MMMMMB   ZMMMMMMMMM@    WMMMMMMMMMMMMMMMM    WMMMMMMMM',
      '  MS   XMMMMMMa    aMMMMMM8   SMMMMMMMMMW    0MMMMMMMMMMMMMMMB    0MMMMMMMM',
      '  MBZZaBMMMMMMM8Z8ZMMMMMMMWZZZ8MMMMMMMMMMZZ8ZMMMMMMMMMMMMMMMMMZ8ZZMMMMMMMMM',
      '  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
      ''].join('\n');
    console.log(content + '\n' + logo);
  }
}